Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -129,24 +129,25 @@ jobs:
           docker push ${{ secrets.DOCKER_USERNAME }}/business-travel-backend:${{ env.tag }}
           
     # Deployment Job
-  deploy:
-    runs-on: ubuntu-latest
-    needs: [frontend, backend, docker]
-    environment:
+    deploy:
+     runs-on: ubuntu-latest
+     needs: [frontend, backend, docker]
+     environment:
       name: ${{ github.ref_name == 'main' && 'Development' || github.ref_name == 'production' && 'Production' }}
+     steps:
+       - name: Checkout code
+         uses: actions/checkout@v3
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Deploy to Development or Production
-        run: |
-          if [[ "${{ github.ref_name }}" == "main" ]]; then
-            echo "Deploying to Development"
+       - name: Deploy to Development or Production
+         run: |
+           if [[ "${GITHUB_REF_NAME}" == "master" || "${GITHUB_REF_NAME}" == "main" ]]; then
+             echo "Deploying to Development"
             # Add deployment commands for Development
-          elif [[ "${{ github.ref_name }}" == "production" ]]; then
-            echo "Deploying to Production"
+           elif [[ "${GITHUB_REF_NAME}" == "production" ]]; then
+             echo "Deploying to Production"
             # Add deployment commands for Production
-          else
-            echo "Invalid branch for deployment. Exiting."
-            exit 1
+           else
+             echo "Invalid branch: ${GITHUB_REF_NAME}. Exiting."
+             exit 1
+           fi
+
